name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Vérifier la structure du repo
        run: ls -R

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.CLE_CAREPLANT }}

      - name: Installer les dépendances et build
        run: |
          ls -R         
          npm install --production
          npm run build

      - name: Déployer sur Hostinger via SCP
        run: |
          scp -r ./CarePlant_Frontend/build/* u607780247@147.93.92.1:/home/u607780247/domains/portefolio.avaulleemanonportefolio.fr/public_html/careplantfront
