name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Vérifier la structure du repo
        run: ls -R

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.CLE_CAREPLANT }}

      
      - name: Installer les dépendances et build
        run: |
          cd careplant_front  # Se déplacer dans le bon dossier
          ls -R               # Vérifier que les fichiers sont bien là
          npm install --production
          npm run build

      - name: Ajouter Hostinger aux hôtes connus
        run: |
          ssh-keyscan -p 65002 147.93.92.1 >> ~/.ssh/known_hosts

      - name: Déployer sur Hostinger via SCP
        run: |
          scp -P 65002 -r ./careplant_front/build/* u607780247@147.93.92.1:/home/u607780247/domains/portefolio.avaulleemanonportefolio.fr/public_html/careplantfront
